name: oidc action GCP

on:
  push:
    tags:
      - "v*"

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write'
      contents: 'read'

    steps:
      # actions/checkout MUST come before auth
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/774923046234/locations/global/workloadIdentityPools/test-kapp-deploy-oidc-pool/providers/test-kapp-deploy-provider'
          service_account: 'kapp-deploy-service-account@sound-yew-356306.iam.gserviceaccount.com'

      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: cluster-yash
          location: us-central1-a

      - id: install-kapp
        uses: vmware-tanzu/carvel-setup-action@v1
        with:
          only: kapp

      - id: 'deploy-with-kapp'
        run: |-
          kapp deploy -a app -f simple-app.yml -y
          kapp ls -A